title: Håndbog til OS2-fællesskabet
description: Praktiske rutiner, værktøjer og principper i OS2 og sekretariatet.
theme: just-the-docs
logo: "/assets/images/os2_logo.png"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

aux_links:
  Repository: https://github.com/zorp/os2-sekretariat-docs
  Maintainers: ./MAINTAINERS
  Contribute: ./CONTRIBUTING