title: Sådan gør vi i OS2-sekretariatet
description: Praktiske rutiner, værktøjer og principper i sekretariatet.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Documentation repository: https://github.com/zorp/os2-sekretariat-docs
