title: Sådan gør vi i OS2-sekretariatet
description: Praktiske rutiner, værktøjer og principper i sekretariatet.
theme: just-the-docs

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

aux_links:
  Repository: https://github.com/zorp/os2-sekretariat-docs
  Maintainers: ./MAINTAINERS
  Contribute: ./CONTRIBUTING