title: Sådan gør vi i OS2-sekretariatet
description: Praktiske rutiner, værktøjer og principper i sekretariatet.
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/zorp/os2-sekretariat-docs
  Maintainers: ./MAINTAINERS
  Contribute: ./CONTRIBUTING