title: Sådan gør vi i OS2-sekretariatet
description: Praktiske rutiner, værktøjer og principper i sekretariatet.
#remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
just_the_docs:
  mermaid: true   # Native Mermaid i v0.6+

plugins:
#  - jekyll-remote-theme
  - jekyll-seo-tag

baseurl: "/os2-sekretariat-docs"
url: "https://zorp.github.io"

aux_links:
  Repository: https://github.com/zorp/os2-sekretariat-docs
  Maintainers: ./MAINTAINERS
  Contribute: ./CONTRIBUTING